NumPy in Python (Numerical python)

- NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.
- It is the fundamental package for scientific computing with Python. It contains various features including these important ones:
- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities
- Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.
- Arbitrary data-types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.


- What are NumPy Arrays?
NumPy is a Python package that stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object.
- Where is NumPy used?
Python NumPy arrays provide tools for integrating C, C++, etc. It is also useful in linear algebra, random number capability etc. NumPy array can also be used as an efficient multi-dimensional container for generic data. Now, let me tell you what exactly is a Python NumPy array.
- Python NumPy Array: Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements. In order to perform these NumPy operations, the next question which will come in your mind is
- How do I install NumPy?
To install Python NumPy, go to your command prompt and type “pip install numpy”. Once the installation is completed, go to your IDE (For example: PyCharm) and simply import it by typing: “import numpy as np”


In [ ]:
import numpy as np

Arrays in numpy

- NumPy’s main object is the homogeneous multidimensional array.
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- In NumPy dimensions are called axes. The number of axes is rank.
- NumPy’s array class is called ndarray. It is also known by the alias array.


Array creation
- There are various ways to create arrays in NumPy.
- For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.
- To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
- arange: returns evenly spaced values within a given interval. step size is specified.
- linspace: returns evenly spaced values within a given interval. num no. of elements are returned.
- Reshaping array: We can use reshape method to reshape an array. 
- Flatten array: We can use flatten method to get a copy of array collapsed into one dimension.


In [2]:
list1=[12,23,'array',45,89,True]
list1

[12, 23, 'array', 45, 89, True]

In [3]:
array=np.array(list1)
array

array(['12', '23', 'array', '45', '89', 'True'], dtype='<U11')

In [4]:
array.ndim

1

In [5]:
array.shape

(6,)

In [6]:
array.size

6

In [7]:
array.dtype

dtype('<U11')

In [9]:
x=[[0,1,2],[3,4,5],[6,7,8]]

array_1=np.array(x)

In [15]:
array_1.ndim

2

In [16]:
array_1.shape

(3, 3)

In [17]:
array_1.size

9

In [18]:
array_1.dtype

dtype('int32')

In [22]:
array_1=np.array([0, 1, 2,3, 4, 5,6, 7, 8])
array_1.shape

(9,)

In [23]:
array_reshaped=array_1.reshape(3,3)
array_reshaped

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
array_reshaped.shape

(3, 3)

In [25]:
array_2=array_reshaped.ravel()
array_2.shape

(9,)

In [26]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])

In [27]:
c=np.concatenate((a,b),axis=None)
c

array([1, 2, 3, 4, 5, 6])

In [31]:
b_transpose=b.T
b_transpose

array([[5],
       [6]])

In [28]:
d=np.concatenate((a,b.T),axis=1)
d

array([[1, 2, 5],
       [3, 4, 6]])

In [29]:
e=np.concatenate((a,b),axis=0)
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
x=np.array([0,1,2,3,4,5,6,7,8])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
y=np.split(x,3)
y

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [43]:
a=np.array([0,1,2,3,4,5,6,7,8])
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
d=np.zeros((3,3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
c=np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
b+c

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [48]:
b-c

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [49]:
b*c

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [50]:
b/c

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [51]:
d=np.dot(b,c)
d

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [53]:
# Solving a system of linear equation

# 4x  + 3y = 20
# -5x + 9y = 26

In [54]:
# In the matrix solution, the system of linear equations to be solved is represented in the form of matrix AX = B
# X = inverse(A).B

In [58]:
import numpy as np

m_list = [[4, 3], [-5, 9]]
A = np.array(m_list)

In [59]:
inv_A = np.linalg.inv(A)

print(inv_A)

[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [60]:
B = np.array([20, 26])
X = np.linalg.inv(A).dot(B)

print(X)

[2. 4.]


In [2]:
x = np.arange(0, np.pi*4, np.pi/4)
x

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([ 0.        ,  0.78539816,  1.57079633,  2.35619449,  3.14159265,
        3.92699082,  4.71238898,  5.49778714,  6.28318531,  7.06858347,
        7.85398163,  8.6393798 ,  9.42477796, 10.21017612, 10.99557429,
       11.78097245])

In [3]:
y=np.sin(x)
y

<IPython.core.display.Javascript object>

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
       -2.44929360e-16,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        3.67394040e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01])

In [4]:
y=np.cos(x)
y

<IPython.core.display.Javascript object>

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00, -7.07106781e-01, -1.83697020e-16,  7.07106781e-01,
        1.00000000e+00,  7.07106781e-01,  3.06161700e-16, -7.07106781e-01,
       -1.00000000e+00, -7.07106781e-01, -4.28626380e-16,  7.07106781e-01])

In [5]:
y=np.tan(x)
y

<IPython.core.display.Javascript object>

array([ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16, -1.00000000e+00,
       -1.22464680e-16,  1.00000000e+00,  5.44374645e+15, -1.00000000e+00,
       -2.44929360e-16,  1.00000000e+00,  3.26624787e+15, -1.00000000e+00,
       -3.67394040e-16,  1.00000000e+00,  2.33303419e+15, -1.00000000e+00])

In [7]:
y=np.exp(x)
y

<IPython.core.display.Javascript object>

array([1.00000000e+00, 2.19328005e+00, 4.81047738e+00, 1.05507241e+01,
       2.31406926e+01, 5.07540195e+01, 1.11317778e+02, 2.44151063e+02,
       5.35491656e+02, 1.17448317e+03, 2.57597050e+03, 5.64982470e+03,
       1.23916478e+04, 2.71783539e+04, 5.96097415e+04, 1.30740857e+05])